### PR TITLE
WIP: Chat SDK V2

### PR DESCRIPTION
**Pull request by ened**
Still a work in progress, but will update this PR with the V2 SDK integration work.

There are a lot of new APIs, which will not be supported from day 1.

### CODE REVIEW

**Comment by ened** [comment]
For anyone interested in trying this out:

In your pubspec.yaml, add the following section:

```
dependency_overrides:
  zendesk:
    git:
      url: https://github.com/ened/flutter-zendesk.git
      ref: v2
```

You may need to change some of the calling code.

Looking forward to community feedback on this PR.

**Comment by mathieusachet** [comment]
I think there is 3 errors compiling for Android. Seems to be ok for iOS.
`/Users/mathieus/Documents/flutter/.pub-cache/git/flutter-zendesk-815250930023fddfca737a0a2d7d2fc4e6b78d59/android/src/main/java/com/codeheadlabs/zendesk/MethodCallHandlerImpl.java:54: error: cannot find symbol
      zopimConfig.department((String) call.argument("department"));
      ^
  symbol:   variable zopimConfig
  location: class MethodCallHandlerImpl
/Users/mathieus/Documents/flutter/.pub-cache/git/flutter-zendesk-815250930023fddfca737a0a2d7d2fc4e6b78d59/android/src/main/java/com/codeheadlabs/zendesk/MethodCallHandlerImpl.java:57: error: cannot find symbol
      zopimConfig.visitorPathOne((String) call.argument("appName"));
      ^
  symbol:   variable zopimConfig
  location: class MethodCallHandlerImpl
/Users/mathieus/Documents/flutter/.pub-cache/git/flutter-zendesk-815250930023fddfca737a0a2d7d2fc4e6b78d59/android/src/main/java/com/codeheadlabs/zendesk/MethodCallHandlerImpl.java:92: error: cannot find symbol
      Intent intent = new Intent(activity, ZopimChatActivity.class);
                                           ^
  symbol:   class ZopimChatActivity
  location: class MethodCallHandlerImpl
3 errors

FAILURE: Build failed with an exception.`

**Comment by emostar** [comment]
Hi @ened 

Thanks for the PR, I really appreciate it! Will you be able to fix the Android issues, so we can merge this in?

**Comment by ened** [comment]
Yes - I'll work on it this week. It's been quite busy, major app release is due to go out. apologies.

**Comment by emostar** [comment]
@ened No worries! I know how busy things can get.

**Comment by alan2030** [comment]
Hi @ened! I was curious if you had any chance to work on it?

**Comment by ened** [comment]
Hi everyone,
The PR has been updated and should now build for everyone. Sorry for the delay.
The plugin is migrated to `pigeon` for improved developer experience (looking forward to PRs, the Zendesk SDK is huge) and some notes on Android have been added to the README.
Happy to hear your thoughts:

```
dependency_overrides:
  zendesk:
    git:
      url: https://github.com/ened/flutter-zendesk.git
      ref: v2
```

**Comment by mjmon** [comment]
@ened Thank you for your work, tested it and Android is working now based on the example.

**Comment by ened** [comment]
@emostar hi there, interested to chat about getting it merged?

**Comment by emostar** [comment]
Hi @ened,

Sorry for the delay. I'd love to get this merged and released, I'll have to test out the example program on iOS and Android first.

Are there any caveats, or things that I should be aware of?

**Comment by ened** [comment]
@emostar No caveats at this moment.
I hope the usage of pigeon for the API calls is a good foundation for the community to bring in the rest of the Zendesk APIs.

**Comment by emostar** [comment]
@ened OK, Sounds good. Looks like @mjmon tested it on Android. I'll do iOS when I get a chance this week.

**Pull request merged**
