### PR TITLE
Android embedding V2

### PR DESCRIPTION
**Pull request by ened**
Based on #13 - this will migrate the plugin to Flutters new V2 embedding for the Android plugin.

More details: https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

### CODE REVIEW

**Comment by ened** [comment]
@emostar (hi) interested?

**Comment by emostar** [comment]
Thanks for the PR! I'm actually not aware of the Android V2 embedding, so I'll go over the doc link that you sent. This sounds like something I would be interested in merging, once I understand it!

**Comment by ened** [comment]
In general the V2 embedding makes the plugin lifecycle a lot clearer. 
Plugins could also run in background services or need to know when they're attached / detached from Android Activities etc. For this plugin, the functionality may not be needed yet; however the zendesk SDKs themselves have a lot of features that aren't implemented yet and this may be a good way to move forward. And also, to get some testing in via the e2e bridge.

Have rebased the PR so it's a bit more clear now.

**Comment by emostar** [comment]
Thanks! Looks good to me. I'll update the pub.dev hosted package soon.

**Pull request merged**
