### PR TITLE
Migrate e2e testing to integration_test

### PR DESCRIPTION
**Pull request by ened**
You can run the test in the example folder, using:

```
fvm flutter drive --driver=test_driver/integration_test.dart --target=integration_test/visitor_info_test.dart
```

We can not bump to Flutter2.x yet as the integration_test and pigeon packages are incompatible with each other. The PRs are on deck, for example here: https://github.com/flutter/packages/pull/315

Looks like migration will be possible with Flutter 2.1+

### CODE REVIEW

**Comment by ened** [comment]
@emostar for your review

**Comment by ryanheise** [comment]
Would be nice to have this merged because the null safety migration (#35 ) can't happen without this.

Regarding pigeon, I've personally stayed away from it as I find it a bit too experimental, incomplete and rough around the edges. A quick and dirty approach to null safety (not worth merging but addressing any immediate needs) would be to migrate the generated pigeon code, so I may try to do that based on this fork.

**Comment by ened** [comment]
@ryanheise things have moved on - pigeon may be a lot more stable now. @emostar do you still have interest in maintaining this plugin?

**Comment by ryanheise** [comment]
My experience with using pigeon on a project was that it was nice, until I ran into a limitation and realised there was no way around it (on that occasion it was that pigeon didn't then support asynchronous methods.) It's slowly gaining more features but there's still just too much missing for now (e.g. https://github.com/flutter/flutter/issues/66711 and https://github.com/flutter/flutter/issues/66710). I'll probably give it another go in a year.

**Comment by ened** [comment]
Yes why not. @emostar Let's do it.

**Comment by emostar** [comment]
@ened I'll need your pub.dev email address to add you to the project.

**Comment by ened** [comment]
> @ened I'll need your pub.dev email address to add you to the project.

<firstname>.<lastname>@gmail.com thx

**Pull request merged**
